In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os,glob
import scipy.interpolate

import scipy.signal


In [188]:

data = np.loadtxt('/tmp/plane_refine.txt', skiprows=1)
#data = np.loadtxt('/home/daniele/Desktop/temp/SisterResults/component_1B.txt', skiprows=1)
#data = data[6:, ::]

bs = np.array([0.002, 0.01,0.025,0.05,0.1,0.15])
hs = np.array([0.01, 0.05,0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55])
#print(data[:,:3])


In [190]:
n = 6
print(data.shape)
for i in range(n):
    rmse = data[i * 6:i * 6 + 6, 4]
    inliers = data[i * 6:i * 6 + 6, 5] 
    
    #rmse = np.clip(rmse, 0 , 10)
    d = rmse
    print(d.ravel())
    #d = (d - np.min(d)) / (np.max(d) - np.min(d))
    
    
    #d = (d - np.min(d)) / (np.max(d)- np.min(d))
    
    
    plt.plot(bs, d);

plt.title("ARDUINO - BASELINE vs DISTANCE")
plt.legend(['Distance {} m'.format(hs[i]) for i in range(n)])
plt.xlabel('baseline [m]')
plt.ylabel('RMSE')
plt.show()

plt.show()

(72, 7)
[2.05842221e-03 2.33209607e+00 2.55840227e+00 2.48935385e+00
 3.22762521e+00 5.44311554e+00]
[1.97904623e-03 2.45799682e-03 2.46452351e+00 1.72552498e+00
 2.81454924e+00 3.32079449e+00]
[3.16971661e-03 2.94033100e-03 2.45092825e-03 1.73389931e+00
 1.73899216e+00 2.68463232e+00]
[0.00816531 0.00324181 0.00310111 0.00296135 2.02059448 2.17836158]
[0.00215146 0.00273337 0.002779   0.00270346 1.73431184 1.49596518]
[0.00242334 0.00325559 0.00350679 0.00320411 1.53044686 1.68564174]


In [191]:
n = 6
min_d = np.min(data[:,3])
max_d = np.max(data[:,3])
for i in range(n):
    d = data[i::6, 2]
    
    #d = d1 / (640*480)
    #plt.plot(xnew, ynew)
    # newx = np.repeat(hs.ravel(),1000)
    # newy = np.repeat(d.ravel(),1000)
    # 
    # print(newy)
    # newy = scipy.signal.medfilt(newy,115)
    # print(newy)
    # f = scipy.interpolate.interp1d(hs, d, fill_value='extrapolate')
    # print(f)
    # xnew = np.arange(0.002, 0.12, 0.0001)
    # print(xnew)
    # ynew = f(xnew)
    # print(ynew)
    # 
    # print(xnew)
    # print(ynew)
    
    #
    #d = (d - np.min(d)) / (np.max(d) - np.min(d))
    
    
    d = np.clip(d, 0, 0.1)
    d = scipy.signal.medfilt(d,3)
    plt.plot(hs,d)
    

plt.title("ARDUINO - DISTANCE vs BASELINE")
plt.legend(['Baseline {} m'.format(bs[i]) for i in range(n)])
plt.xlabel('distance [m]')
plt.ylabel('RMSE')
plt.show()