In [3]:
import numpy as np
import matplotlib.pyplot as plt
import os,glob


In [171]:
data = np.loadtxt('/tmp/cippino_0J.txt', skiprows=1)
#data = data[6:, ::]
bs = np.array([0.0002, 0.01,0.025,0.05,0.1,0.12])
hs = np.array([0.01, 0.05,0.1,0.2,0.3,0.5])
print(data[:,:3])

[[0.00000000e+00 2.00000000e+00 2.81918675e-03]
 [0.00000000e+00 1.00000000e+01 1.29064733e-01]
 [0.00000000e+00 2.50000000e+01 3.00172619e-01]
 [0.00000000e+00 5.00000000e+01 4.69872851e-01]
 [0.00000000e+00 1.00000000e+02 5.95050262e-01]
 [0.00000000e+00 1.20000000e+02 6.04330552e-01]
 [1.00000000e+00 2.00000000e+00 6.27688126e-03]
 [1.00000000e+00 1.00000000e+01 6.40460145e-03]
 [1.00000000e+00 2.50000000e+01 1.11817795e-01]
 [1.00000000e+00 5.00000000e+01 2.50073683e-01]
 [1.00000000e+00 1.00000000e+02 4.05724031e-01]
 [1.00000000e+00 1.20000000e+02 4.32613869e-01]
 [2.00000000e+00 2.00000000e+00 4.36159481e-03]
 [2.00000000e+00 1.00000000e+01 3.76483189e-03]
 [2.00000000e+00 2.50000000e+01 4.02797998e-03]
 [2.00000000e+00 5.00000000e+01 4.36342090e-02]
 [2.00000000e+00 1.00000000e+02 1.69680280e-01]
 [2.00000000e+00 1.20000000e+02 1.93797442e-01]
 [3.00000000e+00 2.00000000e+00 2.05882120e-03]
 [3.00000000e+00 1.00000000e+01 1.87963508e-03]
 [3.00000000e+00 2.50000000e+01 1.952205

In [9]:
print(data.shape)

(36, 9)


In [179]:
n = 6
print(data.shape)
for i in [5]:
    rmse = data[i * 6:i * 6 + 6, 4]
    acc = 1.0 - data[i * 6:i * 6 + 6, 5]
    
    d = rmse * acc
    print(rmse, acc)
    #d = (d - np.min(d)) / (np.max(d)- np.min(d))
    #print(d)
    
    plt.plot(bs, rmse);
plt.show()

(36, 7)
[0.01349209 0.00455643 0.00526612 0.00519485 0.00494228 0.00490057] [-4224. -2830. -2861. -2997. -2836. -2701.]


In [170]:
n = 2
for i in [5]:
    d = data[i::6, 4]
    #d = d1 / (640*480)
    #d = (d - np.min(d)) / (np.max(d)- np.min(d))
        
    print(hs.shape)
    print(d.shape)
    plt.plot(hs, d);
    print(d)

plt.legend(['Distance {} m'.format(bs[i]) for i in range(n)])
plt.xlabel('distance [m]')
plt.ylabel('Normalized Error')
plt.show()

(6,)
(6,)
[0.19506282 0.49484134 0.44984123 0.2392757  0.00565952 0.00569265]
